# Generated by Django 3.0.8 on 2020-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('music', models.CharField(max_length=50)),
                ('tag', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
