# Generated by Django 3.0.8 on 2020-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictest', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='song',
            field=models.FileField(null=True, upload_to='music'),
        ),
    ]
