# Generated by Django 3.0.8 on 2020-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictest', '0008_auto_20200727_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song',
            field=models.FileField(null=True, upload_to='Musiary/'),
        ),
    ]
