# Generated by Django 3.0.8 on 2020-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictest', '0010_remove_post_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album_official',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='albumart_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='artist_official',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lyric_official',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='music_official',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
