# Generated by Django 3.0.8 on 2020-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictest', '0013_auto_20200802_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='albumart_official',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
